name:                ImperativeToTMCompiler
version:             0.1.0.0
github:              "github.com/AlvaroBarroso/ImperativeToTMCompiler"
license:             BSD-3-Clause
author:              "Alvaro Barroso"
maintainer:          "alva15151515@gmail.com"
copyright:           "2024 Alvaro Barroso"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ImperativeToTMCompiler#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ImperativeToTMCompiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImperativeToTMCompiler
    build-tools:
    - alex >= 3.4.0.1
    - happy >= 1.20.1.1
    - BNFC >= 2.9.5
tests:
  ImperativeToTMCompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ImperativeToTMCompiler
